# Generated by Django 3.0.4 on 2020-05-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('mov_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_title', models.CharField(max_length=100)),
                ('en_title', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_collection', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('co_time', models.DateTimeField(null=True)),
                ('co_text', models.TextField(default='')),
                ('content_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.users')),
            ],
        ),
    ]
