# Generated by Django 3.0.4 on 2020-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200505_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='co_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
