# Generated by Django 3.0.4 on 2020-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200505_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('mov_id', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
            ],
        ),
    ]
