# Generated by Django 3.0.4 on 2020-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
